name: Developer tests

on: push

jobs:
  launch-tests:
    runs-on: ubuntu-latest
    container: maven:3.9.6-eclipse-temurin-21

    steps:
      - uses: actions/checkout@v1

      - name: Launch tests with Maven
        working-directory: ./p2-todolist-app
        run: mvn test
